- spring break dates (february-April)
- summer vacation dates (late May-September)
- Thanksgiving Travel (End of November)
- Christmas to New Years (End of December to Early Janurary)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
twentytwenty_tow_accidents = pd.read_csv('C:\\Users\\ksree\\Documents\\dda9\\PYTHON\\PROJECTS\\kristen_r_capstone\\data\\2020_tow_crashes.csv')

In [3]:
twentytwenty_tow_accidents

,Unnamed: 0,"Bus (Seats for 9-15 People, including driver)","Bus (Seats for > 15 People, including driver)","Single Unit Truck, 2 axle, 6 tire","Single Unit Truck, 3+axle","Single Unit Truck, axles unknown",Truck/Trailers,Truck/Tractor (bobtail),Tractor/Semi-trailer,Tractor/Double,Tractor/Triple,"Passenger Car, Only Displays HazMat Placard","Light Truck, Only Display HazMat Placard",Missing,Total
0,Alabama,10,59,687,278,5,181,63,"1,625",26,0,0,0,0,"2,934"
1,Alaska,0,0,0,0,1,0,0,3,1,0,0,0,0,5
2,Arizona,15,81,150,247,144,350,26,771,52,2,0,1,0,"1,839"
3,Arkansas,7,42,273,127,2,80,43,"1,204",23,0,0,0,0,"1,801"
4,California,24,136,"2,181",478,48,610,274,"3,935",506,6,0,1,3,"8,202"
5,Colorado,0,92,282,204,2,32,29,824,28,1,0,0,0,"1,494"
6,Connecticut,4,60,208,102,1,14,1,485,12,0,0,0,0,887
7,Delaware,4,18,107,62,4,12,7,144,1,0,0,0,0,359
8,Dist. Of Columbia,2,24,43,25,2,4,4,1,0,0,0,0,0,105
9,Florida,45,388,"1,214",834,0,205,161,"2,876",44,0,0,0,2,"5,769"
10,Georgia,9,168,580,366,9,82,98,"2,334",35,0,0,0,0,"3,681"
11,Hawaii,6,11,42,9,0,3,0,7,0,0,0,0,0,78
12,Idaho,1,10,61,47,0,24,8,228,30,9,0,0,0,418
13,Illinois,20,179,764,702,505,82,61,"1,825",48,3,0,0,1,"4,190"
14,Indiana,15,138,669,382,8,66,169,"2,321",75,5,0,0,0,"3,848"
15,Iowa,4,47,249,182,0,36,25,897,22,0,0,1,2,"1,465"
16,Kansas,10,43,184,117,9,117,20,851,27,4,0,0,0,"1,382"
17,Kentucky,16,45,260,194,35,184,26,"1,106",30,3,0,0,0,"1,899"
18,Louisiana,9,43,264,143,94,178,29,950,8,0,0,0,0,"1,718"
19,Maine,3,10,142,90,0,21,2,151,1,0,0,0,0,420
20,Maryland,35,91,445,631,22,16,2,718,0,1,0,0,0,"1,961"
21,Massachusetts,31,52,285,117,8,46,14,441,11,0,0,0,0,"1,005"
22,Michigan,49,179,"1,046",336,7,168,57,"1,745",120,0,0,0,0,"3,707"
23,Minnesota,28,99,334,131,56,175,26,685,14,0,0,0,77,"1,625"
24,Mississippi,36,24,218,137,8,139,145,541,17,0,0,0,1,"1,266"
25,Missouri,32,74,773,307,157,43,66,"1,882",62,4,0,0,0,"3,400"
26,Montana,0,9,64,48,5,234,3,158,42,1,0,0,0,564
27,Nebraska,7,8,66,92,20,73,12,405,15,2,0,0,0,700
28,Nevada,2,1,19,11,14,78,3,170,38,12,0,0,0,348
29,New Hampshire,2,9,117,53,0,4,3,105,0,0,0,0,0,293
30,New Jersey,35,202,844,369,86,528,75,731,15,1,0,2,64,"2,952"
31,New Mexico,0,1,25,10,53,23,18,389,10,26,0,0,0,555
32,New York,16,293,"1,313",551,19,613,7,899,35,2,0,0,0,"3,748"
33,North Carolina,11,144,"1,032",490,58,780,74,"1,201",32,0,0,1,91,"3,914"
34,North Dakota,1,10,41,37,80,0,5,214,7,0,0,0,0,395
35,Ohio,242,148,0,0,205,658,0,"2,473",0,0,0,9,0,"3,735"
36,Oklahoma,22,35,546,143,3,382,93,893,31,1,0,0,0,"2,149"
37,Oregon,7,51,218,5,0,82,9,642,100,9,0,0,0,"1,123"
38,Pennsylvania,11,215,865,570,502,332,63,"2,168",39,0,0,0,0,"4,765"
39,Rhode Island,2,7,26,12,3,5,5,38,0,0,0,0,0,98
40,South Carolina,2,24,107,136,85,443,44,485,21,0,0,1,2,"1,350"
41,South Dakota,2,13,25,19,1,8,3,220,12,1,0,0,0,304
42,Tennessee,8,70,413,517,130,495,32,"1,186",62,2,0,1,0,"2,916"
43,Texas,70,376,"1,595",706,117,"1,982",304,"6,070",91,2,0,0,18,"11,331"
44,Utah,1,11,68,35,83,3,274,9,1,0,0,0,0,485
45,Vermont,0,4,15,19,3,33,1,37,1,0,0,1,9,123
46,Virginia,19,74,488,282,5,101,85,"1,531",50,0,0,1,1,"2,637"
47,Washington,2,99,266,193,14,301,22,710,88,0,0,0,0,"1,695"
48,West Virginia,3,30,32,50,3,88,19,438,17,0,0,0,1,681
49,Wisconsin,8,74,294,286,1,38,26,937,20,0,0,1,0,"1,685"
50,Wyoming,1,6,58,37,6,34,6,629,56,1,0,0,0,834

In [4]:
twentytwenty_injury_accidents = pd.read_csv('C:\\Users\\ksree\\Documents\\dda9\\PYTHON\\PROJECTS\\kristen_r_capstone\\data\\2020_injury_crashes.csv')

In [5]:
twentytwenty_injury_accidents

,Unnamed: 0,"Bus (Seats for 9-15 People, including driver)","Bus (Seats for > 15 People, including driver)","Single Unit Truck, 2 axle, 6 tire","Single Unit Truck, 3+axle","Single Unit Truck, axles unknown",Truck/Trailers,Truck/Tractor (bobtail),Tractor/Semi-trailer,Tractor/Double,Tractor/Triple,"Passenger Car, Only Displays HazMat Placard","Light Truck, Only Display HazMat Placard",Missing,Total
0,Alabama,6,29,288,143,9,89,33,735,7,0,0,0,0,"1,339"
1,Alaska,0,0,2,0,0,0,0,0,0,0,0,0,0,2
2,Arizona,2,5,27,36,16,76,4,178,14,0,0,0,0,358
3,Arkansas,12,34,174,82,0,37,24,588,11,0,0,0,0,962
4,California,21,226,"1,292",263,22,263,137,"1,508",206,4,0,0,2,"3,944"
5,Colorado,1,34,82,73,1,11,9,248,6,0,0,0,0,465
6,Connecticut,1,69,100,45,1,5,0,169,3,0,0,0,0,393
7,Delaware,5,23,67,41,1,8,8,85,0,0,0,0,0,238
8,Dist. Of Columbia,3,93,52,24,3,4,7,2,0,0,0,0,1,189
9,Florida,58,418,730,520,1,74,80,"1,509",27,0,0,0,0,"3,417"
10,Georgia,13,139,341,224,1,32,60,"1,216",29,0,0,0,0,"2,055"
11,Hawaii,6,20,28,13,0,0,2,7,0,0,0,0,0,76
12,Idaho,4,11,33,46,0,13,8,140,16,1,0,0,0,272
13,Illinois,23,220,487,407,241,41,27,"1,046",20,2,0,0,2,"2,516"
14,Indiana,13,65,205,144,1,14,57,778,23,3,0,0,0,"1,303"
15,Iowa,2,20,100,78,0,11,4,395,9,0,0,0,2,621
16,Kansas,4,4,66,50,2,32,5,299,4,0,0,0,0,466
17,Kentucky,11,41,128,135,20,94,15,491,12,0,0,0,0,947
18,Louisiana,14,99,287,228,95,157,35,895,6,0,0,3,0,"1,819"
19,Maine,1,7,100,66,0,6,1,120,0,0,0,0,0,301
20,Maryland,53,169,272,374,18,8,3,298,0,0,0,0,0,"1,195"
21,Massachusetts,20,57,157,70,0,16,9,195,1,0,0,0,0,525
22,Michigan,20,80,283,98,0,42,28,465,40,0,0,0,0,"1,056"
23,Minnesota,9,45,113,47,16,64,8,267,2,0,0,0,37,608
24,Mississippi,15,19,156,95,3,89,102,362,13,0,0,0,1,855
25,Missouri,42,124,426,167,65,31,35,832,31,1,0,0,0,"1,754"
26,Montana,1,2,16,21,6,46,3,43,5,1,0,0,0,144
27,Nebraska,15,15,43,69,20,51,7,294,6,2,0,0,0,522
28,Nevada,1,6,17,16,9,27,9,95,14,4,0,0,0,198
29,New Hampshire,2,2,51,17,0,1,0,44,1,0,0,0,0,118
30,New Jersey,36,208,601,313,68,335,53,466,4,3,0,2,48,"2,137"
31,New Mexico,0,2,9,4,13,10,10,193,10,13,0,0,0,264
32,New York,57,671,"1,256",506,27,530,3,525,19,2,0,0,0,"3,596"
33,North Carolina,6,222,905,433,50,556,60,945,25,0,0,0,113,"3,315"
34,North Dakota,0,5,13,24,23,0,1,74,0,1,0,0,0,141
35,Ohio,193,200,0,0,112,383,0,"1,192",0,0,0,2,0,"2,082"
36,Oklahoma,10,22,235,81,4,158,50,383,12,3,0,0,1,959
37,Oregon,0,24,72,5,0,22,1,188,34,3,0,0,0,349
38,Pennsylvania,7,225,446,267,230,137,24,876,16,0,0,0,1,"2,229"
39,Rhode Island,2,10,17,11,2,5,2,22,0,0,0,0,0,71
40,South Carolina,16,55,137,153,78,371,41,447,12,0,0,1,2,"1,313"
41,South Dakota,0,3,4,9,0,2,1,27,2,0,0,0,0,48
42,Tennessee,11,60,208,286,63,213,14,499,27,1,0,0,0,"1,382"
43,Texas,73,321,"1,387",536,54,"1,072",233,"3,785",61,3,0,0,3,"7,528"
44,Utah,3,21,145,61,208,8,402,8,1,0,0,0,0,857
45,Vermont,1,1,9,9,0,19,0,13,1,0,0,0,2,55
46,Virginia,16,67,225,157,1,44,49,658,24,0,0,0,0,"1,241"
47,Washington,0,46,47,42,2,43,3,103,17,0,0,0,0,303
48,West Virginia,2,16,22,32,5,31,7,178,7,0,0,0,0,300
49,Wisconsin,7,63,108,109,0,17,10,343,7,0,0,0,0,664
50,Wyoming,1,3,16,15,2,4,2,164,17,0,0,0,0,224

In [6]:
twentytwenty_fatal_accidents = pd.read_csv('C:\\Users\\ksree\\Documents\\dda9\\PYTHON\\PROJECTS\\kristen_r_capstone\\data\\2020_fatal_crashes.csv')

In [7]:
twentytwenty_fatal_accidents

,Unnamed: 0,"Bus (Seats for 9-15 People, including driver)","Bus (Seats for > 15 People, including driver)","Single Unit Truck, 2 axle, 6 tire","Single Unit Truck, 3+axle","Single Unit Truck, axles unknown",Truck/Trailers,Truck/Tractor (bobtail),Tractor/Semi-trailer,Tractor/Double,Tractor/Triple,"Passenger Car, Only Displays HazMat Placard","Light Truck, Only Display HazMat Placard",Missing,Total
0,Alabama,0,4,25,20,2,4,3,87,1,0,0,0,0,146
1,Alaska,0,0,0,1,1,1,0,2,0,0,0,0,0,5
2,Arizona,1,2,15,12,8,11,1,57,5,0,0,0,1,113
3,Arkansas,1,1,19,5,0,2,0,61,0,0,0,0,0,89
4,California,1,17,125,23,5,45,16,200,34,1,0,0,0,467
5,Colorado,1,5,26,6,0,8,1,40,0,0,0,0,0,87
6,Connecticut,0,0,11,1,0,1,0,18,0,0,0,0,0,31
7,Delaware,0,1,4,1,0,0,2,2,0,0,0,0,0,10
8,Dist. Of Columbia,0,1,1,0,0,0,0,0,0,0,0,0,0,2
9,Florida,3,11,101,53,0,15,8,172,6,0,0,0,0,369
10,Georgia,3,8,48,28,1,9,4,141,2,0,0,0,0,244
11,Hawaii,0,1,5,0,0,1,1,0,0,0,0,0,0,8
12,Idaho,0,0,7,5,0,2,0,21,6,1,0,0,0,42
13,Illinois,2,2,30,25,9,5,2,88,5,0,0,0,1,169
14,Indiana,2,4,36,20,0,1,1,96,4,0,0,0,0,164
15,Iowa,0,2,12,13,0,0,0,41,2,0,0,0,0,70
16,Kansas,0,2,9,4,0,5,1,56,1,0,0,0,0,78
17,Kentucky,1,2,29,9,1,8,1,57,0,0,0,0,0,108
18,Louisiana,0,5,12,7,2,8,3,58,0,0,0,0,0,95
19,Maine,0,1,9,5,0,1,0,3,0,0,0,0,0,19
20,Maryland,1,2,23,15,1,0,0,23,0,0,0,0,0,65
21,Massachusetts,0,0,9,2,0,0,2,14,0,0,0,0,0,27
22,Michigan,0,6,19,9,0,5,1,36,2,0,0,0,0,78
23,Minnesota,0,1,10,12,0,9,0,29,0,0,0,0,0,61
24,Mississippi,0,1,8,12,3,10,9,52,1,0,0,0,0,96
25,Missouri,1,3,27,19,6,3,3,63,2,0,0,0,0,127
26,Montana,0,2,3,2,0,8,0,5,1,0,0,0,0,21
27,Nebraska,0,0,2,6,0,4,1,33,2,0,0,0,0,48
28,Nevada,1,4,1,0,2,5,2,9,3,2,0,0,0,29
29,New Hampshire,0,0,2,3,0,0,0,2,0,0,0,0,0,7
30,New Jersey,0,8,12,14,2,5,3,23,0,0,0,0,1,68
31,New Mexico,0,1,4,0,5,6,2,40,1,0,0,0,0,59
32,New York,1,14,40,27,0,15,2,39,0,0,1,0,0,139
33,North Carolina,0,9,29,23,0,23,2,65,4,0,0,0,2,157
34,North Dakota,0,0,0,0,2,0,0,13,0,0,0,0,0,15
35,Ohio,5,4,0,0,8,35,0,89,0,0,0,0,0,141
36,Oklahoma,1,0,17,7,0,18,2,47,1,0,0,0,0,93
37,Oregon,0,1,9,1,0,3,0,30,6,0,0,0,0,50
38,Pennsylvania,0,9,26,25,15,8,2,77,0,0,0,0,0,162
39,Rhode Island,0,0,0,3,0,0,0,4,0,0,0,0,0,7
40,South Carolina,0,3,31,28,0,21,3,39,2,0,0,0,1,128
41,South Dakota,1,0,5,3,1,0,1,11,1,0,0,0,0,23
42,Tennessee,0,4,42,29,2,14,5,86,2,0,0,0,0,184
43,Texas,3,8,124,39,1,74,10,407,10,0,0,0,0,676
44,Utah,0,1,2,6,7,1,19,1,0,0,0,0,0,37
45,Vermont,0,0,1,1,0,2,0,0,0,0,0,0,0,4
46,Virginia,3,4,16,6,0,1,2,71,7,0,0,0,0,110
47,Washington,0,3,15,12,0,5,1,14,4,0,0,0,0,54
48,West Virginia,0,1,11,3,4,2,0,14,0,0,0,0,0,35
49,Wisconsin,0,3,14,9,0,0,2,36,1,0,0,0,0,65
50,Wyoming,1,0,3,2,2,3,2,44,1,0,0,0,0,58

In [8]:
missing_nc1 = twentytwenty_tow_accidents.loc[twentytwenty_tow_accidents.Missing == 91]

In [9]:
missing_nc1

,Unnamed: 0,"Bus (Seats for 9-15 People, including driver)","Bus (Seats for > 15 People, including driver)","Single Unit Truck, 2 axle, 6 tire","Single Unit Truck, 3+axle","Single Unit Truck, axles unknown",Truck/Trailers,Truck/Tractor (bobtail),Tractor/Semi-trailer,Tractor/Double,Tractor/Triple,"Passenger Car, Only Displays HazMat Placard","Light Truck, Only Display HazMat Placard",Missing,Total
33,North Carolina,11,144,"1,032",490,58,780,74,"1,201",32,0,0,1,91,"3,914"

In [10]:
missing_nc2 = twentytwenty_injury_accidents.loc[twentytwenty_injury_accidents.Missing == 113]

In [11]:
missing_nc2

,Unnamed: 0,"Bus (Seats for 9-15 People, including driver)","Bus (Seats for > 15 People, including driver)","Single Unit Truck, 2 axle, 6 tire","Single Unit Truck, 3+axle","Single Unit Truck, axles unknown",Truck/Trailers,Truck/Tractor (bobtail),Tractor/Semi-trailer,Tractor/Double,Tractor/Triple,"Passenger Car, Only Displays HazMat Placard","Light Truck, Only Display HazMat Placard",Missing,Total
33,North Carolina,6,222,905,433,50,556,60,945,25,0,0,0,113,"3,315"